# Hydra Configuration File
params:
  batchsize: 5
  num_workers: 1
  num_epochs: 2
  random_flip: true

optimizer:
  SGD:
    lr: 0.01  # Learning rate for the alternate optimizer
    momentum: 0.9
  Adam:
    lr: 1e-5
    
model_params:
  UnetModel:
    hidden_size: 128
    out_channel: 3
    in_channel: 3

  DiffusionModel:
    betas: [1e-4, 0.02]
    num_timesteps: 1000
